//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SneakerInsideAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog
    {
        public Catalog()
        {
            this.Products = new HashSet<Product>();
            this.SubCatalogs = new HashSet<SubCatalog>();
        }
    
        public int CatalogID { get; set; }
        public string CatalogName { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<SubCatalog> SubCatalogs { get; set; }
    }
}
