//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SneakerInsideAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SneakerDBEntities : DbContext
    {
        public SneakerDBEntities()
            : base("name=SneakerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Catalog> Catalogs { get; set; }
        public DbSet<District> Districts { get; set; }
        public DbSet<ImageProduct> ImageProducts { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductItem> ProductItems { get; set; }
        public DbSet<Province> Provinces { get; set; }
        public DbSet<Size> Sizes { get; set; }
        public DbSet<SubCatalog> SubCatalogs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserOrder> UserOrders { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
    
        public virtual int Admin_Delete(Nullable<int> adminID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var adminIDParameter = adminID.HasValue ?
                new ObjectParameter("AdminID", adminID) :
                new ObjectParameter("AdminID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Admin_Delete", adminIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<Admin_GetAll_Result> Admin_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Admin_GetAll_Result>("Admin_GetAll");
        }
    
        public virtual ObjectResult<Admin_GetItemById_Result> Admin_GetItemById(Nullable<int> adminID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var adminIDParameter = adminID.HasValue ?
                new ObjectParameter("AdminID", adminID) :
                new ObjectParameter("AdminID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Admin_GetItemById_Result>("Admin_GetItemById", adminIDParameter, errorCode, errorMessage);
        }
    
        public virtual int Admin_Insert(string account, string password, string name, Nullable<int> role, ObjectParameter errorMessage)
        {
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var roleParameter = role.HasValue ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Admin_Insert", accountParameter, passwordParameter, nameParameter, roleParameter, errorMessage);
        }
    
        public virtual int Admin_Update(Nullable<int> adminID, string account, string password, string name, Nullable<int> role, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var adminIDParameter = adminID.HasValue ?
                new ObjectParameter("AdminID", adminID) :
                new ObjectParameter("AdminID", typeof(int));
    
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var roleParameter = role.HasValue ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Admin_Update", adminIDParameter, accountParameter, passwordParameter, nameParameter, roleParameter, errorCode, errorMessage);
        }
    
        public virtual int Catalog_Delete(Nullable<int> catalogID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var catalogIDParameter = catalogID.HasValue ?
                new ObjectParameter("CatalogID", catalogID) :
                new ObjectParameter("CatalogID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Catalog_Delete", catalogIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<Catalog_GetAll_Result> Catalog_GetAll(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Catalog_GetAll_Result>("Catalog_GetAll", errorCode, errorMessage);
        }
    
        public virtual ObjectResult<Catalog_GetItemById_Result> Catalog_GetItemById(Nullable<int> catalogID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var catalogIDParameter = catalogID.HasValue ?
                new ObjectParameter("CatalogID", catalogID) :
                new ObjectParameter("CatalogID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Catalog_GetItemById_Result>("Catalog_GetItemById", catalogIDParameter, errorCode, errorMessage);
        }
    
        public virtual int Catalog_Insert(string catalogName, Nullable<int> status, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var catalogNameParameter = catalogName != null ?
                new ObjectParameter("CatalogName", catalogName) :
                new ObjectParameter("CatalogName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Catalog_Insert", catalogNameParameter, statusParameter, errorCode, errorMessage);
        }
    
        public virtual int Catalog_Update(Nullable<int> catalogID, string catalogName, Nullable<int> status, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var catalogIDParameter = catalogID.HasValue ?
                new ObjectParameter("CatalogID", catalogID) :
                new ObjectParameter("CatalogID", typeof(int));
    
            var catalogNameParameter = catalogName != null ?
                new ObjectParameter("CatalogName", catalogName) :
                new ObjectParameter("CatalogName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Catalog_Update", catalogIDParameter, catalogNameParameter, statusParameter, errorCode, errorMessage);
        }
    
        public virtual int ChangePassword(Nullable<int> adminID, string newPassword, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var adminIDParameter = adminID.HasValue ?
                new ObjectParameter("AdminID", adminID) :
                new ObjectParameter("AdminID", typeof(int));
    
            var newPasswordParameter = newPassword != null ?
                new ObjectParameter("NewPassword", newPassword) :
                new ObjectParameter("NewPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangePassword", adminIDParameter, newPasswordParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<DashBoard_GetCountProductByCatalogName_Result> DashBoard_GetCountProductByCatalogName(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DashBoard_GetCountProductByCatalogName_Result>("DashBoard_GetCountProductByCatalogName", errorCode, errorMessage);
        }
    
        public virtual ObjectResult<DashBoard_GetOrderStatus_Result> DashBoard_GetOrderStatus(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DashBoard_GetOrderStatus_Result>("DashBoard_GetOrderStatus", errorCode, errorMessage);
        }
    
        public virtual ObjectResult<DashBoard_GetTop10ProductOrder_Result> DashBoard_GetTop10ProductOrder(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DashBoard_GetTop10ProductOrder_Result>("DashBoard_GetTop10ProductOrder", errorCode, errorMessage);
        }
    
        public virtual int District_Delete(Nullable<int> districtID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var districtIDParameter = districtID.HasValue ?
                new ObjectParameter("DistrictID", districtID) :
                new ObjectParameter("DistrictID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("District_Delete", districtIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<District_GetAll_Result> District_GetAll(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<District_GetAll_Result>("District_GetAll", errorCode, errorMessage);
        }
    
        public virtual ObjectResult<District_GetItemById_Result> District_GetItemById(Nullable<int> districtID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var districtIDParameter = districtID.HasValue ?
                new ObjectParameter("DistrictID", districtID) :
                new ObjectParameter("DistrictID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<District_GetItemById_Result>("District_GetItemById", districtIDParameter, errorCode, errorMessage);
        }
    
        public virtual int District_Insert(string districtName, Nullable<int> status, Nullable<int> provinceID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var districtNameParameter = districtName != null ?
                new ObjectParameter("DistrictName", districtName) :
                new ObjectParameter("DistrictName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var provinceIDParameter = provinceID.HasValue ?
                new ObjectParameter("ProvinceID", provinceID) :
                new ObjectParameter("ProvinceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("District_Insert", districtNameParameter, statusParameter, provinceIDParameter, errorCode, errorMessage);
        }
    
        public virtual int District_Update(Nullable<int> districtID, string districtName, Nullable<int> status, Nullable<int> provinceID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var districtIDParameter = districtID.HasValue ?
                new ObjectParameter("DistrictID", districtID) :
                new ObjectParameter("DistrictID", typeof(int));
    
            var districtNameParameter = districtName != null ?
                new ObjectParameter("DistrictName", districtName) :
                new ObjectParameter("DistrictName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var provinceIDParameter = provinceID.HasValue ?
                new ObjectParameter("ProvinceID", provinceID) :
                new ObjectParameter("ProvinceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("District_Update", districtIDParameter, districtNameParameter, statusParameter, provinceIDParameter, errorCode, errorMessage);
        }
    
        public virtual int ImageProduct_Delete(Nullable<int> imageID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var imageIDParameter = imageID.HasValue ?
                new ObjectParameter("ImageID", imageID) :
                new ObjectParameter("ImageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ImageProduct_Delete", imageIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<ImageProduct_GetAll_Result> ImageProduct_GetAll(Nullable<int> productID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ImageProduct_GetAll_Result>("ImageProduct_GetAll", productIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<ImageProduct_GetItemById_Result> ImageProduct_GetItemById(Nullable<int> imageID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var imageIDParameter = imageID.HasValue ?
                new ObjectParameter("ImageID", imageID) :
                new ObjectParameter("ImageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ImageProduct_GetItemById_Result>("ImageProduct_GetItemById", imageIDParameter, errorCode, errorMessage);
        }
    
        public virtual int ImageProduct_Insert(Nullable<int> productID, string image, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            var imageParameter = image != null ?
                new ObjectParameter("Image", image) :
                new ObjectParameter("Image", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ImageProduct_Insert", productIDParameter, imageParameter, errorCode, errorMessage);
        }
    
        public virtual int ImageProduct_Update(Nullable<int> imageID, string image, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var imageIDParameter = imageID.HasValue ?
                new ObjectParameter("ImageID", imageID) :
                new ObjectParameter("ImageID", typeof(int));
    
            var imageParameter = image != null ?
                new ObjectParameter("Image", image) :
                new ObjectParameter("Image", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ImageProduct_Update", imageIDParameter, imageParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<IS_GetProductByCatalog_Result> IS_GetProductByCatalog(Nullable<int> catalogID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var catalogIDParameter = catalogID.HasValue ?
                new ObjectParameter("CatalogID", catalogID) :
                new ObjectParameter("CatalogID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IS_GetProductByCatalog_Result>("IS_GetProductByCatalog", catalogIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<IS_GetSubCatalogByCatalog_Result> IS_GetSubCatalogByCatalog(Nullable<int> catalogID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var catalogIDParameter = catalogID.HasValue ?
                new ObjectParameter("CatalogID", catalogID) :
                new ObjectParameter("CatalogID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IS_GetSubCatalogByCatalog_Result>("IS_GetSubCatalogByCatalog", catalogIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<Login_Result> Login(string account, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Login_Result>("Login", accountParameter, errorCode, errorMessage);
        }
    
        public virtual int Order_ChangeStatus(Nullable<int> userOrderID, Nullable<int> status, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var userOrderIDParameter = userOrderID.HasValue ?
                new ObjectParameter("UserOrderID", userOrderID) :
                new ObjectParameter("UserOrderID", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Order_ChangeStatus", userOrderIDParameter, statusParameter, errorCode, errorMessage);
        }
    
        public virtual int Order_Destroy(Nullable<int> userOrderID, Nullable<int> productItemID, Nullable<int> amountStock, Nullable<int> amountBuy, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var userOrderIDParameter = userOrderID.HasValue ?
                new ObjectParameter("UserOrderID", userOrderID) :
                new ObjectParameter("UserOrderID", typeof(int));
    
            var productItemIDParameter = productItemID.HasValue ?
                new ObjectParameter("ProductItemID", productItemID) :
                new ObjectParameter("ProductItemID", typeof(int));
    
            var amountStockParameter = amountStock.HasValue ?
                new ObjectParameter("AmountStock", amountStock) :
                new ObjectParameter("AmountStock", typeof(int));
    
            var amountBuyParameter = amountBuy.HasValue ?
                new ObjectParameter("AmountBuy", amountBuy) :
                new ObjectParameter("AmountBuy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Order_Destroy", userOrderIDParameter, productItemIDParameter, amountStockParameter, amountBuyParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<Order_GetAll_Result> Order_GetAll(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order_GetAll_Result>("Order_GetAll", errorCode, errorMessage);
        }
    
        public virtual ObjectResult<Order_GetDetail_Result> Order_GetDetail(Nullable<int> userOrderID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var userOrderIDParameter = userOrderID.HasValue ?
                new ObjectParameter("UserOrderID", userOrderID) :
                new ObjectParameter("UserOrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order_GetDetail_Result>("Order_GetDetail", userOrderIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<Order_GetDetail_For_Destroy_Result> Order_GetDetail_For_Destroy(Nullable<int> userOrderID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var userOrderIDParameter = userOrderID.HasValue ?
                new ObjectParameter("UserOrderID", userOrderID) :
                new ObjectParameter("UserOrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order_GetDetail_For_Destroy_Result>("Order_GetDetail_For_Destroy", userOrderIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<Order_GetOrderByStatus_Result> Order_GetOrderByStatus(Nullable<int> status, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order_GetOrderByStatus_Result>("Order_GetOrderByStatus", statusParameter, errorCode, errorMessage);
        }
    
        public virtual int OS_ChangeInfo(Nullable<int> userID, string fullName, string phoneNumber, string email, string address, Nullable<int> provinceID, Nullable<int> districtID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var provinceIDParameter = provinceID.HasValue ?
                new ObjectParameter("ProvinceID", provinceID) :
                new ObjectParameter("ProvinceID", typeof(int));
    
            var districtIDParameter = districtID.HasValue ?
                new ObjectParameter("DistrictID", districtID) :
                new ObjectParameter("DistrictID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OS_ChangeInfo", userIDParameter, fullNameParameter, phoneNumberParameter, emailParameter, addressParameter, provinceIDParameter, districtIDParameter, errorCode, errorMessage);
        }
    
        public virtual int OS_ChangePassword(Nullable<int> userID, string newPassword, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var newPasswordParameter = newPassword != null ?
                new ObjectParameter("NewPassword", newPassword) :
                new ObjectParameter("NewPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OS_ChangePassword", userIDParameter, newPasswordParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<OS_GetAllCatalog_Result> OS_GetAllCatalog(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OS_GetAllCatalog_Result>("OS_GetAllCatalog", errorCode, errorMessage);
        }
    
        public virtual ObjectResult<OS_GetAllDistrict_Result> OS_GetAllDistrict(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OS_GetAllDistrict_Result>("OS_GetAllDistrict", errorCode, errorMessage);
        }
    
        public virtual ObjectResult<OS_GetAllOrder_Result> OS_GetAllOrder(Nullable<int> userID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OS_GetAllOrder_Result>("OS_GetAllOrder", userIDParameter, errorCode, errorMessage);
        }
    
        public virtual int OS_GetAllProduct(string inSort, Nullable<int> catalogID, Nullable<int> subCatalogID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var inSortParameter = inSort != null ?
                new ObjectParameter("InSort", inSort) :
                new ObjectParameter("InSort", typeof(string));
    
            var catalogIDParameter = catalogID.HasValue ?
                new ObjectParameter("CatalogID", catalogID) :
                new ObjectParameter("CatalogID", typeof(int));
    
            var subCatalogIDParameter = subCatalogID.HasValue ?
                new ObjectParameter("SubCatalogID", subCatalogID) :
                new ObjectParameter("SubCatalogID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OS_GetAllProduct", inSortParameter, catalogIDParameter, subCatalogIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<OS_GetAllProvince_Result> OS_GetAllProvince(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OS_GetAllProvince_Result>("OS_GetAllProvince", errorCode, errorMessage);
        }
    
        public virtual ObjectResult<OS_GetDistrictByProvince_Result> OS_GetDistrictByProvince(Nullable<int> provinceID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var provinceIDParameter = provinceID.HasValue ?
                new ObjectParameter("ProvinceID", provinceID) :
                new ObjectParameter("ProvinceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OS_GetDistrictByProvince_Result>("OS_GetDistrictByProvince", provinceIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<string> OS_GetImageProductByID(Nullable<int> productID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("OS_GetImageProductByID", productIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<OS_GetOrderDetail_Result> OS_GetOrderDetail(Nullable<int> userOrderID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var userOrderIDParameter = userOrderID.HasValue ?
                new ObjectParameter("UserOrderID", userOrderID) :
                new ObjectParameter("UserOrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OS_GetOrderDetail_Result>("OS_GetOrderDetail", userOrderIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<OS_GetProductDetailByID_Result> OS_GetProductDetailByID(Nullable<int> productID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OS_GetProductDetailByID_Result>("OS_GetProductDetailByID", productIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<OS_GetProductDetailInCart_Result> OS_GetProductDetailInCart(Nullable<int> productID, Nullable<int> sizeID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            var sizeIDParameter = sizeID.HasValue ?
                new ObjectParameter("SizeID", sizeID) :
                new ObjectParameter("SizeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OS_GetProductDetailInCart_Result>("OS_GetProductDetailInCart", productIDParameter, sizeIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<OS_GetSizeProductByID_Result> OS_GetSizeProductByID(Nullable<int> productID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OS_GetSizeProductByID_Result>("OS_GetSizeProductByID", productIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<OS_GetSubCatalogByCatalog_Result> OS_GetSubCatalogByCatalog(Nullable<int> catalogID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var catalogIDParameter = catalogID.HasValue ?
                new ObjectParameter("CatalogID", catalogID) :
                new ObjectParameter("CatalogID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OS_GetSubCatalogByCatalog_Result>("OS_GetSubCatalogByCatalog", catalogIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<OS_GetTop10NewProduct_Result> OS_GetTop10NewProduct(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OS_GetTop10NewProduct_Result>("OS_GetTop10NewProduct", errorCode, errorMessage);
        }
    
        public virtual ObjectResult<OS_GetTop10SaleProduct_Result> OS_GetTop10SaleProduct(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OS_GetTop10SaleProduct_Result>("OS_GetTop10SaleProduct", errorCode, errorMessage);
        }
    
        public virtual ObjectResult<OS_Login_Result> OS_Login(string account, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OS_Login_Result>("OS_Login", accountParameter, errorCode, errorMessage);
        }
    
        public virtual int OS_Payment_LoginUser(string iN_JSON, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var iN_JSONParameter = iN_JSON != null ?
                new ObjectParameter("IN_JSON", iN_JSON) :
                new ObjectParameter("IN_JSON", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OS_Payment_LoginUser", iN_JSONParameter, errorCode, errorMessage);
        }
    
        public virtual int OS_Payment_NormalUser(string iN_JSON, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var iN_JSONParameter = iN_JSON != null ?
                new ObjectParameter("IN_JSON", iN_JSON) :
                new ObjectParameter("IN_JSON", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OS_Payment_NormalUser", iN_JSONParameter, errorCode, errorMessage);
        }
    
        public virtual int OS_SearchProduct(string inSort, string content, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var inSortParameter = inSort != null ?
                new ObjectParameter("InSort", inSort) :
                new ObjectParameter("InSort", typeof(string));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OS_SearchProduct", inSortParameter, contentParameter, errorCode, errorMessage);
        }
    
        public virtual int OS_SignUp(string account, string password, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OS_SignUp", accountParameter, passwordParameter, errorCode, errorMessage);
        }
    
        public virtual int OS_UpdateAmountStock(Nullable<int> productItemID, Nullable<int> amountStock, Nullable<int> amountBuy, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var productItemIDParameter = productItemID.HasValue ?
                new ObjectParameter("ProductItemID", productItemID) :
                new ObjectParameter("ProductItemID", typeof(int));
    
            var amountStockParameter = amountStock.HasValue ?
                new ObjectParameter("AmountStock", amountStock) :
                new ObjectParameter("AmountStock", typeof(int));
    
            var amountBuyParameter = amountBuy.HasValue ?
                new ObjectParameter("AmountBuy", amountBuy) :
                new ObjectParameter("AmountBuy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OS_UpdateAmountStock", productItemIDParameter, amountStockParameter, amountBuyParameter, errorCode, errorMessage);
        }
    
        public virtual int Product_Delete(Nullable<int> productID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Product_Delete", productIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<Product_GetAll_Result> Product_GetAll(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Product_GetAll_Result>("Product_GetAll", errorCode, errorMessage);
        }
    
        public virtual ObjectResult<Product_GetItemById_Result> Product_GetItemById(Nullable<int> productID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Product_GetItemById_Result>("Product_GetItemById", productIDParameter, errorCode, errorMessage);
        }
    
        public virtual int Product_Insert(string productName, string description, Nullable<double> price, Nullable<int> status, Nullable<int> catalogID, Nullable<int> subCatalogID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(double));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var catalogIDParameter = catalogID.HasValue ?
                new ObjectParameter("CatalogID", catalogID) :
                new ObjectParameter("CatalogID", typeof(int));
    
            var subCatalogIDParameter = subCatalogID.HasValue ?
                new ObjectParameter("SubCatalogID", subCatalogID) :
                new ObjectParameter("SubCatalogID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Product_Insert", productNameParameter, descriptionParameter, priceParameter, statusParameter, catalogIDParameter, subCatalogIDParameter, errorCode, errorMessage);
        }
    
        public virtual int Product_Update(Nullable<int> productID, string productName, string description, Nullable<double> price, Nullable<int> status, Nullable<int> catalogID, Nullable<int> subCatalogID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(double));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var catalogIDParameter = catalogID.HasValue ?
                new ObjectParameter("CatalogID", catalogID) :
                new ObjectParameter("CatalogID", typeof(int));
    
            var subCatalogIDParameter = subCatalogID.HasValue ?
                new ObjectParameter("SubCatalogID", subCatalogID) :
                new ObjectParameter("SubCatalogID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Product_Update", productIDParameter, productNameParameter, descriptionParameter, priceParameter, statusParameter, catalogIDParameter, subCatalogIDParameter, errorCode, errorMessage);
        }
    
        public virtual int ProductItem_Delete(Nullable<int> productItemID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var productItemIDParameter = productItemID.HasValue ?
                new ObjectParameter("ProductItemID", productItemID) :
                new ObjectParameter("ProductItemID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductItem_Delete", productItemIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<ProductItem_GetAll_Result> ProductItem_GetAll(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductItem_GetAll_Result>("ProductItem_GetAll", errorCode, errorMessage);
        }
    
        public virtual ObjectResult<ProductItem_GetItemById_Result> ProductItem_GetItemById(Nullable<int> productItemID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var productItemIDParameter = productItemID.HasValue ?
                new ObjectParameter("ProductItemID", productItemID) :
                new ObjectParameter("ProductItemID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductItem_GetItemById_Result>("ProductItem_GetItemById", productItemIDParameter, errorCode, errorMessage);
        }
    
        public virtual int ProductItem_Insert(Nullable<int> productID, Nullable<int> sizeID, Nullable<int> amountStock, Nullable<int> status, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            var sizeIDParameter = sizeID.HasValue ?
                new ObjectParameter("SizeID", sizeID) :
                new ObjectParameter("SizeID", typeof(int));
    
            var amountStockParameter = amountStock.HasValue ?
                new ObjectParameter("AmountStock", amountStock) :
                new ObjectParameter("AmountStock", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductItem_Insert", productIDParameter, sizeIDParameter, amountStockParameter, statusParameter, errorCode, errorMessage);
        }
    
        public virtual int ProductItem_Update(Nullable<int> productItemID, Nullable<int> productID, Nullable<int> sizeID, Nullable<int> amountStock, Nullable<int> status, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var productItemIDParameter = productItemID.HasValue ?
                new ObjectParameter("ProductItemID", productItemID) :
                new ObjectParameter("ProductItemID", typeof(int));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            var sizeIDParameter = sizeID.HasValue ?
                new ObjectParameter("SizeID", sizeID) :
                new ObjectParameter("SizeID", typeof(int));
    
            var amountStockParameter = amountStock.HasValue ?
                new ObjectParameter("AmountStock", amountStock) :
                new ObjectParameter("AmountStock", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductItem_Update", productItemIDParameter, productIDParameter, sizeIDParameter, amountStockParameter, statusParameter, errorCode, errorMessage);
        }
    
        public virtual int Province_Delete(Nullable<int> provinceID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var provinceIDParameter = provinceID.HasValue ?
                new ObjectParameter("ProvinceID", provinceID) :
                new ObjectParameter("ProvinceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Province_Delete", provinceIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<Province_GetAll_Result> Province_GetAll(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Province_GetAll_Result>("Province_GetAll", errorCode, errorMessage);
        }
    
        public virtual ObjectResult<Province_GetItemById_Result> Province_GetItemById(Nullable<int> provinceID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var provinceIDParameter = provinceID.HasValue ?
                new ObjectParameter("ProvinceID", provinceID) :
                new ObjectParameter("ProvinceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Province_GetItemById_Result>("Province_GetItemById", provinceIDParameter, errorCode, errorMessage);
        }
    
        public virtual int Province_Insert(string provinceName, Nullable<int> status, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var provinceNameParameter = provinceName != null ?
                new ObjectParameter("ProvinceName", provinceName) :
                new ObjectParameter("ProvinceName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Province_Insert", provinceNameParameter, statusParameter, errorCode, errorMessage);
        }
    
        public virtual int Province_Update(Nullable<int> provinceID, string provinceName, Nullable<int> status, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var provinceIDParameter = provinceID.HasValue ?
                new ObjectParameter("ProvinceID", provinceID) :
                new ObjectParameter("ProvinceID", typeof(int));
    
            var provinceNameParameter = provinceName != null ?
                new ObjectParameter("ProvinceName", provinceName) :
                new ObjectParameter("ProvinceName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Province_Update", provinceIDParameter, provinceNameParameter, statusParameter, errorCode, errorMessage);
        }
    
        public virtual int Size_Delete(Nullable<int> sizeID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var sizeIDParameter = sizeID.HasValue ?
                new ObjectParameter("SizeID", sizeID) :
                new ObjectParameter("SizeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Size_Delete", sizeIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<Size_GetAll_Result> Size_GetAll(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Size_GetAll_Result>("Size_GetAll", errorCode, errorMessage);
        }
    
        public virtual ObjectResult<Size_GetItemById_Result> Size_GetItemById(Nullable<int> sizeID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var sizeIDParameter = sizeID.HasValue ?
                new ObjectParameter("SizeID", sizeID) :
                new ObjectParameter("SizeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Size_GetItemById_Result>("Size_GetItemById", sizeIDParameter, errorCode, errorMessage);
        }
    
        public virtual int Size_Insert(string sizeName, Nullable<int> status, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var sizeNameParameter = sizeName != null ?
                new ObjectParameter("SizeName", sizeName) :
                new ObjectParameter("SizeName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Size_Insert", sizeNameParameter, statusParameter, errorCode, errorMessage);
        }
    
        public virtual int Size_Update(Nullable<int> sizeID, string sizeName, Nullable<int> status, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var sizeIDParameter = sizeID.HasValue ?
                new ObjectParameter("SizeID", sizeID) :
                new ObjectParameter("SizeID", typeof(int));
    
            var sizeNameParameter = sizeName != null ?
                new ObjectParameter("SizeName", sizeName) :
                new ObjectParameter("SizeName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Size_Update", sizeIDParameter, sizeNameParameter, statusParameter, errorCode, errorMessage);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Statistic_GetAmountStock_Result> Statistic_GetAmountStock(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Statistic_GetAmountStock_Result>("Statistic_GetAmountStock", errorCode, errorMessage);
        }
    
        public virtual int Statistic_GetListOrder(Nullable<int> month, Nullable<int> year, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Statistic_GetListOrder", monthParameter, yearParameter, errorCode, errorMessage);
        }
    
        public virtual int SubCatalog_Delete(Nullable<int> subCatalogID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var subCatalogIDParameter = subCatalogID.HasValue ?
                new ObjectParameter("SubCatalogID", subCatalogID) :
                new ObjectParameter("SubCatalogID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SubCatalog_Delete", subCatalogIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<SubCatalog_GetAll_Result> SubCatalog_GetAll(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubCatalog_GetAll_Result>("SubCatalog_GetAll", errorCode, errorMessage);
        }
    
        public virtual ObjectResult<SubCatalog_GetItemById_Result> SubCatalog_GetItemById(Nullable<int> subCatalogID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var subCatalogIDParameter = subCatalogID.HasValue ?
                new ObjectParameter("SubCatalogID", subCatalogID) :
                new ObjectParameter("SubCatalogID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubCatalog_GetItemById_Result>("SubCatalog_GetItemById", subCatalogIDParameter, errorCode, errorMessage);
        }
    
        public virtual int SubCatalog_Insert(string subCatalogName, Nullable<int> status, Nullable<int> catalogID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var subCatalogNameParameter = subCatalogName != null ?
                new ObjectParameter("SubCatalogName", subCatalogName) :
                new ObjectParameter("SubCatalogName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var catalogIDParameter = catalogID.HasValue ?
                new ObjectParameter("CatalogID", catalogID) :
                new ObjectParameter("CatalogID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SubCatalog_Insert", subCatalogNameParameter, statusParameter, catalogIDParameter, errorCode, errorMessage);
        }
    
        public virtual int SubCatalog_Update(Nullable<int> subCatalogID, string subCatalogName, Nullable<int> status, Nullable<int> catalogID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var subCatalogIDParameter = subCatalogID.HasValue ?
                new ObjectParameter("SubCatalogID", subCatalogID) :
                new ObjectParameter("SubCatalogID", typeof(int));
    
            var subCatalogNameParameter = subCatalogName != null ?
                new ObjectParameter("SubCatalogName", subCatalogName) :
                new ObjectParameter("SubCatalogName", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var catalogIDParameter = catalogID.HasValue ?
                new ObjectParameter("CatalogID", catalogID) :
                new ObjectParameter("CatalogID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SubCatalog_Update", subCatalogIDParameter, subCatalogNameParameter, statusParameter, catalogIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<UserLogin_GetAll_Result> UserLogin_GetAll(ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserLogin_GetAll_Result>("UserLogin_GetAll", errorCode, errorMessage);
        }
    
        public virtual ObjectResult<UserLogin_GetAllOrder_Result> UserLogin_GetAllOrder(Nullable<int> userID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserLogin_GetAllOrder_Result>("UserLogin_GetAllOrder", userIDParameter, errorCode, errorMessage);
        }
    
        public virtual ObjectResult<UserLogin_GetOrderDetail_Result> UserLogin_GetOrderDetail(Nullable<int> userOrderID, ObjectParameter errorCode, ObjectParameter errorMessage)
        {
            var userOrderIDParameter = userOrderID.HasValue ?
                new ObjectParameter("UserOrderID", userOrderID) :
                new ObjectParameter("UserOrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserLogin_GetOrderDetail_Result>("UserLogin_GetOrderDetail", userOrderIDParameter, errorCode, errorMessage);
        }
    }
}
