//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SneakerInsideAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int UserOrderID { get; set; }
        public int ProductItemID { get; set; }
        public int AmountBuy { get; set; }
        public double Total { get; set; }
    
        public virtual ProductItem ProductItem { get; set; }
        public virtual UserOrder UserOrder { get; set; }
    }
}
