//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SneakerInsideAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductItem
    {
        public ProductItem()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ProductItemID { get; set; }
        public int ProductID { get; set; }
        public int SizeID { get; set; }
        public int AmountStock { get; set; }
        public int Status { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Size Size { get; set; }
    }
}
