//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SneakerInsideAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ImageProducts = new HashSet<ImageProduct>();
            this.ProductItems = new HashSet<ProductItem>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int Status { get; set; }
        public int CatalogID { get; set; }
        public int SubCatalogID { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual ICollection<ImageProduct> ImageProducts { get; set; }
        public virtual SubCatalog SubCatalog { get; set; }
        public virtual ICollection<ProductItem> ProductItems { get; set; }
    }
}
