//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SneakerInsideAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public Province()
        {
            this.Districts = new HashSet<District>();
            this.Users = new HashSet<User>();
        }
    
        public int ProvinceID { get; set; }
        public string ProvinceName { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<District> Districts { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
