//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SneakerInsideAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCatalog
    {
        public SubCatalog()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int SubCatalogID { get; set; }
        public string SubCatalogName { get; set; }
        public int Status { get; set; }
        public int CatalogID { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
